[build]
  base = "client"
  command = "npm run build"
  publish = "client/build"

[dev]
  base = "client"
  command = "npm start"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"
