[build]
  base = "client"  # Base directory where your frontend project is located
  command = "npm run build"  # Command to build your frontend project
  publish = "client/build"  # Directory where your frontend build files will be located

[dev]
  base = "client"  # Base directory for local development (if different from production)
  command = "npm start"  # Command to run your local development server

[context.production.environment]
  NODE_ENV = "production"  # Environment variables specific to production

[context.deploy-preview.environment]
  NODE_ENV = "development"  # Environment variables specific to deploy previews

[context.branch-deploy.environment]
  NODE_ENV = "development"  # Environment variables specific to branch deploys
